services:
  postgres:
    image: postgres:17-alpine
    container_name: app-postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: src
      dockerfile: user_service/Dockerfile
    container_name: app-auth
    env_file:
      - src/.env
    environment:

      DATABASE_HOST: postgres
      DATABASE_PORT: 5432

    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy


    command: [ "uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]


volumes:
  pgdata: