events {}

http {
    upstream user_service {
        server user-service:8000;
    }

    upstream file_storage {
        server file-storage:8001;
    }

    server {
        listen 80;


        location /v1/api/auth/ {
            rewrite ^/v1/api/auth/(.*)$ /$1 break;

            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Cookie $http_cookie;
        }


        location = /_auth_identify {
            internal;

            proxy_pass http://user_service/api/v1/auth/internal/identify;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";

            proxy_set_header Authorization $http_authorization;


            proxy_set_header Cookie $http_cookie;
        }

        location = /v1/api/files/docs {
            rewrite ^/v1/api/files/(.*)$ /$1 break;
            proxy_pass http://file_storage;
            proxy_set_header Host $host;
        }

        location = /v1/api/files/openapi.json {
            rewrite ^/v1/api/files/(.*)$ /$1 break;
            proxy_pass http://file_storage;
            proxy_set_header Host $host;
        }


        location /v1/api/files/ {
            auth_request /_auth_identify;

            # Забираем header из ответа user_service:
            # X-k4S-User-Id -> nginx variable: $upstream_http_x_user_id
            auth_request_set $user_id $upstream_http_x_k4s_user_id;

            rewrite ^/v1/api/files/(.*)$ /$1 break;

            proxy_pass http://file_storage;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Прокидываем identity в file-storage
            proxy_set_header X-k4S-User-Id $user_id;
        }
    }
}